# Generated by Django 5.1.3 on 2024-11-27 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo_list", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="content",
            field=models.CharField(max_length=100),
        ),
    ]
