# Generated by Django 5.1.3 on 2024-11-27 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo_list", "0002_alter_task_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="tasks", to="todo_list.tag"
            ),
        ),
    ]
