# Generated by Django 5.1.3 on 2024-11-27 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo_list", "0004_alter_task_tags"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["is_completed", "-created_at"]},
        ),
    ]
